### DISCUSSION TITLE
Verifying creation of index

### DISCUSSION THREAD

**Discussion by ahsanbagwan** [yahoo/elide#1809] [Elide 4]
This application is running as docker container. Also when I run this on local I don't see a `/var/solr` created.

1) How do I verify the index is created?
2) Am I right in setting the indexOnStartup to `true`?

So I have this code in the application.yml

```
search:                               
  jmx_enabled: true                   
  default:                            
    directory_provider: filesystem    
    indexBase: /var/solr              
  generate_statistics: true           
  lucene_version: LUCENE_CURRENT      
```

and the `indexOnStartup` is set to `true` like so

```
@Bean
  SearchDataStore searchStore(SpringHibernateDataStore springHibernateDataStore, EntityManagerFactory entityManagerFactory) {
    return new SearchDataStore(springHibernateDataStore, entityManagerFactory,true);
  }
```
