### ISSUE TITLE
elide-spring-boot-starter:7.0.0-pr5 doesn't work with spring boot 3.1.1

### ISSUE THREAD

**Issue by ynixt** [yahoo/elide#3031]
## Current Behavior
The following exception is throw:
``
org.springframework.beans.factory.BeanCreationException: Error creating bean with name 'scopedTarget.queryRunners' defined in class path resource [com/yahoo/elide/spring/config/ElideAutoConfiguration$RefreshableConfiguration$GraphQLConfiguration.class]: Failed to instantiate [com.yahoo.elide.graphql.QueryRunners]: Factory method 'queryRunners' threw exception with message: null
``
```java

```

## Steps to Reproduce (for bugs)

1. Follow the start guide [https://elide.io/pages/guide/v7/01-start.html](https://elide.io/pages/guide/v7/01-start.html)

## Your Environment

* Elide version used: 7.0.0-pr5
* Environment name and version (Java 1.8.0_152): Java 20.0.1
* Operating System and version: Windows
* Link to your project:

**Comment by justin-tay** [comment]
I have tried but failed the reproduce the issue. Can you provide the project you are using or a minimum reproduction using https://github.com/yahoo/elide-spring-boot-example/tree/elide-7.x?

One thing I noticed is that you are using the refreshable configuration so if you are using elide-spring-boot-example you need to set `spring.cloud.refresh.enabled=true` to replicate your setup.

**Comment by ynixt** [comment]
Project example [https://github.com/ynixt/test-elide](https://github.com/ynixt/test-elide)

In a brief summary:

Is a kotlin project with:
- spring boot 3.1.1
- h2 memory
- elide-spring-boot-starter:7.0.0-pr5
- flyway


the application.yml contains

```yaml
elide:
  json-api:
    path: /api/v1
    enabled: true
  graphql:
    path: /graphql/api/v1
    enabled: true
  api-docs:
    path: /doc
    enabled: true
    version: openapi_3_0
```
